#!/usr/bin/env bash
# Fresh Debian/Ubuntu installation; reviewed against 3x-ui v3.8.0.
set -Eeuo pipefail
umask 077

readonly XUI_VERSION=v3.8.0
readonly PANEL_PORT=2053 SUB_PORT=2096
WORK_DIR=''
XUI_OWNED=0
CADDY_CONFIGURED=0
CADDY_MASKED=0
COMPLETE=0

log() { printf '\n[3x-ui + Caddy] %s\n' "$*"; }
die() { printf '错误：%s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'
用途：全新安装 3x-ui + Caddy，面板和订阅只监听 127.0.0.1。
系统：Debian 12+ / Ubuntu 22.04+，systemd，amd64 / arm64。
用法：sudo bash install-3x-ui-caddy.sh panel.example.com
也可输入：https://panel.example.com 或 https://panel.example.com:443/
预览：bash install-3x-ui-caddy.sh --render panel.example.com

先将域名 A/AAAA 记录指向服务器，并放行 TCP 80、443（保留 SSH）。
Ubuntu 安装前会更新软件源并升级已安装的软件包，不自动重启。
脚本不修改防火墙，不覆盖已有 3x-ui/Caddy，不创建代理节点。
登录信息保存在 /root/3x-ui-caddy-access.txt（权限 600）。
EOF
}

normalize_domain_input() {
    local input="$1"
    local markdown_link='^\[[^][]+\]\((https?://[^[:space:]()]*)\)$'
    # Accept pasted browser addresses, including links copied from chat.
    input="${input#"${input%%[![:space:]]*}"}"
    input="${input%"${input##*[![:space:]]}"}"
    input="${input,,}"
    if [[ "$input" =~ $markdown_link ]]; then
        input="${BASH_REMATCH[1]}"
    fi
    case "$input" in
        https://*) input="${input#https://}" ;;
        http://*) input="${input#http://}" ;;
    esac
    input="${input%/}"
    input="${input%:443}"
    printf '%s' "$input"
}

validate_domain() {
    local domain="$1" label
    [[ ${#domain} -le 253 && "$domain" == *.* ]] || return 1
    [[ "$domain" =~ ^[a-z0-9.-]+$ && ! "$domain" =~ ^[0-9.]+$ ]] || return 1
    [[ "$domain" != *. && "$domain" != *..* ]] || return 1
    local -a labels
    IFS=. read -r -a labels <<< "$domain"
    for label in "${labels[@]}"; do
        [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
        [[ "$label" != -* && "$label" != *- ]] || return 1
    done
    [[ ${#label} -ge 2 && ! "$label" =~ ^[0-9]+$ ]]
}

render_caddyfile() {
    cat <<EOF
# Generated by install-3x-ui-caddy.sh
$DOMAIN {
    encode zstd gzip
    header -Server
    header Strict-Transport-Security "max-age=31536000"

    # Preserve the base path; handle_path would strip it and break 3x-ui.
    redir $PANEL_PATH ${PANEL_PATH}/ 308
    handle ${PANEL_PATH}/* {
        reverse_proxy 127.0.0.1:$PANEL_PORT {
            # 3x-ui's HTTP backend does not mark its session cookies Secure.
            header_down Set-Cookie "^(.*)$" "\$1; Secure"
        }
    }

    @subscription path ${SUB_PATH}/* ${JSON_PATH}/* ${CLASH_PATH}/*
    handle @subscription {
        reverse_proxy 127.0.0.1:$SUB_PORT
    }

    handle {
        respond "Not Found" 404
    }
}
EOF
}

# CLI initialization creates the schema and hashes the random credentials.
# Subscription settings have no equivalent CLI flags in this pinned version.
# Write them in one parameterized transaction while the service is stopped.
configure_database() {
    python3 - "$1" "$DOMAIN" "$PANEL_PORT" "$SUB_PORT" \
        "$PANEL_PATH" "$SUB_PATH" "$JSON_PATH" "$CLASH_PATH" <<'PY'
import sqlite3
import sys
from pathlib import Path

db, domain, panel_port, sub_port, panel, sub, json_path, clash = sys.argv[1:]
if not Path(db).is_file():
    raise SystemExit("3x-ui 没有创建数据库，停止安装。")
settings = {
    "webListen": "127.0.0.1", "webPort": panel_port,
    "webDomain": domain, "webBasePath": panel + "/",
    "webCertFile": "", "webKeyFile": "",
    "trustedProxyCIDRs": "127.0.0.1/32,::1/128",
    "subEnable": "true", "subListen": "127.0.0.1", "subPort": sub_port,
    "subDomain": domain, "subCertFile": "", "subKeyFile": "",
    "subPath": sub + "/", "subURI": "https://" + domain + sub + "/",
    "subJsonEnable": "true", "subJsonPath": json_path + "/",
    "subJsonURI": "https://" + domain + json_path + "/",
    "subClashEnable": "true", "subClashPath": clash + "/",
    "subClashURI": "https://" + domain + clash + "/",
}
with sqlite3.connect(db) as conn:
    columns = {row[1] for row in conn.execute("PRAGMA table_info(settings)")}
    if not {"key", "value"} <= columns:
        raise SystemExit("数据库结构不兼容，停止安装。")
    if conn.execute("SELECT count(*) FROM users").fetchone()[0] != 1:
        raise SystemExit("初始管理员数量异常，停止安装。")
    for key, value in settings.items():
        conn.execute("DELETE FROM settings WHERE key = ?", (key,))
        conn.execute("INSERT INTO settings (key, value) VALUES (?, ?)", (key, value))
    actual = dict(conn.execute("SELECT key, value FROM settings"))
    if any(actual.get(key) != value for key, value in settings.items()):
        raise SystemExit("数据库设置回读失败。")
PY
}

verify_login() {
    python3 - "$DOMAIN" "$PANEL_PORT" "$PANEL_PATH" "$1" "$2" <<'PY'
import http.cookiejar
import json
import sys
import urllib.parse
import urllib.request

domain, port, path, username, password = sys.argv[1:]
client = urllib.request.build_opener(
    urllib.request.ProxyHandler({}),
    urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()),
)
base = "http://127.0.0.1:" + port + path
req = urllib.request.Request(base + "/csrf-token", headers={"Host": domain})
with client.open(req, timeout=10) as response:
    token = json.load(response)["obj"]
payload = urllib.parse.urlencode({"username": username, "password": password}).encode()
req = urllib.request.Request(base + "/login", data=payload,
                             headers={"Host": domain, "X-CSRF-Token": token})
with client.open(req, timeout=10) as response:
    if json.load(response).get("success") is not True:
        raise SystemExit("随机管理员凭据验证失败。")
print("随机管理员凭据验证通过。")
PY
}

cleanup() {
    local status=$?
    trap - EXIT
    if (( status != 0 && COMPLETE == 0 )); then
        if (( XUI_OWNED )); then
            systemctl disable --now x-ui >/dev/null 2>&1 || true
        fi
        if (( CADDY_CONFIGURED )); then
            systemctl disable --now caddy >/dev/null 2>&1 || true
        fi
        if (( CADDY_MASKED )); then
            systemctl unmask caddy >/dev/null 2>&1 || true
        fi
        printf '\n安装未完成。已停用本次配置的服务；文件和日志保留以便排查。\n' >&2
        printf '查看日志：journalctl -u x-ui -u caddy -n 80 --no-pager\n' >&2
        [[ -z "$WORK_DIR" ]] || printf '本次工作目录：%s\n' "$WORK_DIR" >&2
    elif [[ -n "$WORK_DIR" ]]; then
        rm -rf -- "$WORK_DIR"
    fi
    exit "$status"
}

port_busy() {
    [[ -n "$(ss -H -ltn "sport = :$1")" || -n "$(ss -H -lun "sport = :$1")" ]]
}

check_loopback() {
    local port="$1" addresses
    addresses=$(ss -H -ltn "sport = :$port" | awk '{print $4}')
    [[ "$addresses" == "127.0.0.1:$port" ]] || \
        die "端口 $port 未严格绑定 127.0.0.1，已拒绝完成安装。"
}

download() {
    curl --fail --location --silent --show-error --retry 3 \
        --connect-timeout 15 --max-time 600 --proto '=https' --proto-redir '=https' \
        --output "$2" "$1"
}

update_system() {
    log '更新软件源索引；任一软件源更新失败时停止安装。'
    export DEBIAN_FRONTEND=noninteractive
    apt-get -o APT::Update::Error-Mode=any update
    if [[ "$ID" == ubuntu ]]; then
        log '升级 Ubuntu 已安装的软件包，保留已有配置文件。'
        apt-get -o DPkg::Lock::Timeout=120 \
            -o Dpkg::Options::=--force-confdef \
            -o Dpkg::Options::=--force-confold upgrade -y
    fi
}

main() {
    local render=0 arch checksum item username password ready=0
    case "${1:-}" in
        -h|--help) usage; return 0 ;;
        --render) render=1; shift ;;
    esac
    (( $# <= 1 )) || die '只接受一个域名参数。'
    DOMAIN="${1:-}"
    if [[ -z "$DOMAIN" ]]; then
        [[ -t 0 ]] || die '请提供域名，例如：sudo bash install-3x-ui-caddy.sh panel.example.com'
        read -r -p '请输入面板域名或网址（例如 https://panel.example.com）：' DOMAIN
    fi
    DOMAIN=$(normalize_domain_input "$DOMAIN")
    validate_domain "$DOMAIN" || die '请输入有效域名或 http(s) 网址；不支持页面路径、查询参数或非 443 端口，中文域名请使用 punycode。'
    if (( render )); then
        PANEL_PATH=/panel-preview SUB_PATH=/sub-preview
        JSON_PATH=/json-preview CLASH_PATH=/clash-preview
        render_caddyfile
        return 0
    fi

    [[ $EUID -eq 0 ]] || die '请使用 root 或 sudo 运行。'
    [[ "$(uname -s)" == Linux ]] || die '安装目标必须为 Linux。'
    [[ -d /run/systemd/system ]] || die '需要正在运行的 systemd。'
    command -v flock >/dev/null || die '缺少 flock，请安装 util-linux。'
    exec 9>/run/lock/3x-ui-caddy-install.lock
    flock -n 9 || die '另一个安装任务正在运行。'
    # shellcheck disable=SC1091
    source /etc/os-release
    case "${ID:-}:${VERSION_ID:-}" in
        debian:*) [[ "${VERSION_ID%%.*}" =~ ^[0-9]+$ ]] && (( ${VERSION_ID%%.*} >= 12 )) || die '需要 Debian 12+。' ;;
        ubuntu:*) [[ "${VERSION_ID%%.*}" =~ ^[0-9]+$ ]] && (( ${VERSION_ID%%.*} >= 22 )) || die '需要 Ubuntu 22.04+。' ;;
        *) die '此脚本支持 Debian 12+ / Ubuntu 22.04+。' ;;
    esac
    case "$(uname -m)" in
        x86_64) arch=amd64; checksum=236b837627520f0c4ae4134dc6a34ea5e294b69e158879795fe8cd51c5f3582c ;;
        aarch64|arm64) arch=arm64; checksum=e93b7a6ba83bace11c5bf2192a15ae0eec24b1c02496567149fce0d223aba309 ;;
        *) die '当前只支持 amd64 / arm64。' ;;
    esac

    # Refuse existing state instead of treating a second run as an upgrade.
    for item in /usr/local/x-ui /etc/x-ui /usr/bin/x-ui /usr/local/bin/x-ui \
        /etc/default/x-ui /etc/sysconfig/x-ui /etc/conf.d/x-ui \
        /etc/caddy /root/3x-ui-caddy-access.txt \
        /etc/apt/sources.list.d/caddy-stable.list \
        /usr/share/keyrings/caddy-stable-archive-keyring.gpg; do
        [[ ! -e "$item" && ! -L "$item" ]] || die "检测到已有文件 $item。此脚本只用于全新安装。"
    done
    for item in x-ui caddy; do
        if command -v "$item" >/dev/null 2>&1 || \
            [[ "$(systemctl show "$item.service" -p LoadState --value)" != not-found ]]; then
            die "检测到已有 $item，停止以保护现有配置。"
        fi
    done
    for item in $(compgen -e); do
        [[ "$item" != XUI_* ]] || die "请清除已有环境变量 $item 后重试。"
    done
    command -v ss >/dev/null || die '缺少 ss，请先执行 apt-get update && apt-get install -y iproute2。'
    for item in 80 443 2019 "$PANEL_PORT" "$SUB_PORT"; do
        port_busy "$item" && die "端口 $item 已被占用，请先处理冲突。"
    done
    trap cleanup EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM
    WORK_DIR=$(mktemp -d /tmp/3x-ui-caddy.XXXXXXXX)

    update_system
    log '安装基础工具；下载固定版本的官方发行包并校验 SHA-256。'
    apt-get install -y ca-certificates curl gnupg debian-keyring \
        debian-archive-keyring apt-transport-https python3 tar openssl iproute2
    download "https://github.com/MHSanaei/3x-ui/releases/download/$XUI_VERSION/x-ui-linux-$arch.tar.gz" "$WORK_DIR/x-ui.tar.gz"
    printf '%s  %s\n' "$checksum" "$WORK_DIR/x-ui.tar.gz" | sha256sum --check --status || die '3x-ui 发行包校验失败。'
    tar -xzf "$WORK_DIR/x-ui.tar.gz" -C "$WORK_DIR"
    [[ -f "$WORK_DIR/x-ui/x-ui" && -d "$WORK_DIR/x-ui/bin" ]] || die '发行包结构不符合预期。'

    username="u$(openssl rand -hex 5)"
    password=$(openssl rand -hex 18)
    PANEL_PATH="/panel-$(openssl rand -hex 12)"
    SUB_PATH="/sub-$(openssl rand -hex 12)"
    JSON_PATH="/json-$(openssl rand -hex 12)"
    CLASH_PATH="/clash-$(openssl rand -hex 12)"
    install -d -m 700 /etc/x-ui
    mv "$WORK_DIR/x-ui" /usr/local/x-ui
    chmod 755 /usr/local/x-ui/x-ui
    find /usr/local/x-ui/bin -maxdepth 1 -type f -name 'xray-linux-*' -exec chmod 755 {} +
    [[ ! -f /usr/local/x-ui/x-ui.sh ]] || install -m 755 /usr/local/x-ui/x-ui.sh /usr/bin/x-ui
    export XUI_DB_FOLDER=/etc/x-ui XUI_DB_TYPE=sqlite
    (
        cd /usr/local/x-ui
        ./x-ui setting -username "$username" -password "$password" \
            -port "$PANEL_PORT" -listenIP 127.0.0.1 -webBasePath "${PANEL_PATH}/"
    ) > "$WORK_DIR/initialize.log" 2>&1
    configure_database /etc/x-ui/x-ui.db
    chmod 600 /etc/x-ui/x-ui.db

    cat > /root/3x-ui-caddy-access.txt <<EOF
3x-ui $XUI_VERSION + Caddy
面板：https://$DOMAIN${PANEL_PATH}/
用户名：$username
密码：$password
普通订阅：https://$DOMAIN${SUB_PATH}/<客户端订阅ID>
JSON 订阅：https://$DOMAIN${JSON_PATH}/<客户端订阅ID>
Clash 订阅：https://$DOMAIN${CLASH_PATH}/<客户端订阅ID>
面板监听：127.0.0.1:$PANEL_PORT
订阅监听：127.0.0.1:$SUB_PORT
EOF
    chmod 600 /root/3x-ui-caddy-access.txt

    cat > "$WORK_DIR/x-ui.service" <<'EOF'
[Unit]
Description=3x-ui panel (Caddy reverse proxy)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/usr/local/x-ui
Environment=XUI_DB_FOLDER=/etc/x-ui
Environment=XUI_DB_TYPE=sqlite
ExecStart=/usr/local/x-ui/x-ui
Restart=on-failure
RestartSec=5s
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
    install -m 644 "$WORK_DIR/x-ui.service" /etc/systemd/system/x-ui.service
    XUI_OWNED=1
    systemctl daemon-reload

    log '从 Caddy 官方软件源安装；生成 HTTPS 反向代理配置。'
    download 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' "$WORK_DIR/caddy.asc"
    gpg --batch --yes --dearmor --output "$WORK_DIR/caddy.gpg" "$WORK_DIR/caddy.asc"
    install -m 644 "$WORK_DIR/caddy.gpg" /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    download 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' "$WORK_DIR/caddy.list"
    install -m 644 "$WORK_DIR/caddy.list" /etc/apt/sources.list.d/caddy-stable.list
    apt-get update
    # Prevent the package post-install hook from exposing its default site.
    CADDY_CONFIGURED=1
    systemctl mask caddy.service
    CADDY_MASKED=1
    apt-get install -y caddy
    cp -a /etc/caddy/Caddyfile "$WORK_DIR/Caddyfile.package-default"
    render_caddyfile > "$WORK_DIR/Caddyfile"
    caddy fmt --overwrite "$WORK_DIR/Caddyfile"
    caddy validate --config "$WORK_DIR/Caddyfile" --adapter caddyfile
    install -o root -g caddy -m 640 "$WORK_DIR/Caddyfile" /etc/caddy/Caddyfile

    log '启动服务并验证本机监听地址。'
    systemctl enable --now x-ui
    for item in {1..30}; do
        if curl --noproxy '*' -fsS --max-time 2 -H "Host: $DOMAIN" \
            "http://127.0.0.1:$PANEL_PORT${PANEL_PATH}/" -o /dev/null && \
            [[ -n "$(ss -H -ltn "sport = :$SUB_PORT")" ]]; then
            ready=1
            break
        fi
        sleep 1
    done
    (( ready )) || die '3x-ui 没有正常启动。'
    check_loopback "$PANEL_PORT"
    check_loopback "$SUB_PORT"
    verify_login "$username" "$password"
    systemctl unmask caddy.service
    CADDY_MASKED=0
    systemctl enable --now caddy
    systemctl is-active --quiet x-ui caddy || die '服务未处于运行状态。'

    log '等待 HTTPS 证书，最多约 90 秒。'
    ready=0
    for item in {1..18}; do
        if curl --noproxy '*' -fsS --connect-timeout 2 --max-time 3 \
            --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN${PANEL_PATH}/" -o /dev/null 2>/dev/null; then
            ready=1
            break
        fi
        sleep 2
    done
    # TLS pending is recoverable: leave Caddy running so ACME can retry.
    COMPLETE=1
    if (( ready )); then
        log '安装完成，本机 HTTPS 面板访问成功。'
    else
        log '服务已安装且内部端口已绑定本机；HTTPS 尚未验证成功。'
        printf '请检查域名 A/AAAA、云安全组和 TCP 80/443；Caddy 会自动重试签发证书。\n'
    fi
    printf '\n面板：https://%s%s/\n' "$DOMAIN" "$PANEL_PATH"
    printf '用户名和密码：sudo cat /root/3x-ui-caddy-access.txt\n'
    printf '配置：/etc/caddy/Caddyfile\n日志：journalctl -u x-ui -u caddy -n 80 --no-pager\n'
    printf '仍需在外部设备验证域名可访问、2053/2096 不可直连。\n'
    if [[ -f /var/run/reboot-required ]]; then
        printf '系统更新提示需要重启，请在安装完成后择机手动重启服务器。\n'
    fi
    (( ready )) || return 2
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
