#!/usr/bin/env bash
# Fresh Debian/Ubuntu installation; reviewed against 3x-ui v3.8.0.
set -Eeuo pipefail
umask 077

readonly XUI_VERSION=v3.8.0
readonly PANEL_PORT=2053 SUB_PORT=2096 CADDY_TLS_PORT=8443
WORK_DIR=''
XUI_OWNED=0
CADDY_CONFIGURED=0
CADDY_MASKED=0
COMPLETE=0
MIGRATION_STARTED=0
MIGRATION_DB_READY=0
MIGRATION_MUTATED=0
BACKUP_DIR=''
XRAY_BINARY=''
readonly NODE_INFO=/root/3x-ui-reality-node.json

log() { printf '\n[3x-ui + Caddy] %s\n' "$*"; }
die() { printf '错误：%s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'
用途：3x-ui + Caddy + VLESS/TCP/REALITY，共用公网 TCP 443。
系统：Debian 12+ / Ubuntu 22.04+，systemd，amd64 / arm64。
用法：sudo bash install-3x-ui-caddy.sh panel.example.com
也可输入：https://panel.example.com 或 https://panel.example.com:443/
预览：bash install-3x-ui-caddy.sh --render panel.example.com
迁移旧脚本安装：sudo bash install-3x-ui-caddy.sh --migrate panel.example.com

先将域名 A/AAAA 记录指向服务器，并放行 TCP 80、443（保留 SSH）。
Ubuntu 安装前会更新软件源并升级已安装的软件包，不自动重启。
自动创建一个 REALITY 入站和客户端；不修改防火墙。
全新安装拒绝覆盖已有服务；--migrate 会备份并迁移本脚本的已有安装。
登录信息保存在 /root/3x-ui-caddy-access.txt（权限 600）。
节点信息保存在 /root/3x-ui-reality-node.json（权限 600）。
EOF
}

normalize_domain_input() {
    local input="$1"
    local markdown_link='^\[[^][]+\]\((https?://[^[:space:]()]*)\)$'
    # Accept pasted browser addresses, including links copied from chat.
    input="${input#"${input%%[![:space:]]*}"}"
    input="${input%"${input##*[![:space:]]}"}"
    input="${input,,}"
    if [[ "$input" =~ $markdown_link ]]; then
        input="${BASH_REMATCH[1]}"
    fi
    case "$input" in
        https://*) input="${input#https://}" ;;
        http://*) input="${input#http://}" ;;
    esac
    input="${input%/}"
    input="${input%:443}"
    printf '%s' "$input"
}

validate_domain() {
    local domain="$1" label
    [[ ${#domain} -le 253 && "$domain" == *.* ]] || return 1
    [[ "$domain" =~ ^[a-z0-9.-]+$ && ! "$domain" =~ ^[0-9.]+$ ]] || return 1
    [[ "$domain" != *. && "$domain" != *..* ]] || return 1
    local -a labels
    IFS=. read -r -a labels <<< "$domain"
    for label in "${labels[@]}"; do
        [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
        [[ "$label" != -* && "$label" != *- ]] || return 1
    done
    [[ ${#label} -ge 2 && ! "$label" =~ ^[0-9]+$ ]]
}

render_legacy_caddyfile() {
    cat <<EOF
# Generated by install-3x-ui-caddy.sh
$DOMAIN {
    encode zstd gzip
    header -Server
    header Strict-Transport-Security "max-age=31536000"

    # Preserve the base path; handle_path would strip it and break 3x-ui.
    redir $PANEL_PATH ${PANEL_PATH}/ 308
    handle ${PANEL_PATH}/* {
        reverse_proxy 127.0.0.1:$PANEL_PORT {
            # 3x-ui's HTTP backend does not mark its session cookies Secure.
            header_down Set-Cookie "^(.*)$" "\$1; Secure"
        }
    }

    @subscription path ${SUB_PATH}/* ${JSON_PATH}/* ${CLASH_PATH}/*
    handle @subscription {
        reverse_proxy 127.0.0.1:$SUB_PORT
    }

    handle {
        respond "Not Found" 404
    }
}
EOF
}

render_caddyfile() {
    cat <<EOF
# Generated by install-3x-ui-caddy.sh
{
    auto_https disable_redirects
    servers {
        protocols h1 h2
    }
}

# HTTP-01 certificates are renewed on public port 80, independently of Xray.
http://$DOMAIN {
    redir https://$DOMAIN{uri} 308
}

# Xray owns public TCP 443 and forwards ordinary TLS to this loopback listener.
https://$DOMAIN:$CADDY_TLS_PORT {
    bind 127.0.0.1
    tls {
        issuer acme {
            disable_tlsalpn_challenge
        }
    }
    encode zstd gzip
    header -Server
    header Strict-Transport-Security "max-age=31536000"
    redir $PANEL_PATH ${PANEL_PATH}/ 308
    handle ${PANEL_PATH}/* {
        reverse_proxy 127.0.0.1:$PANEL_PORT {
            header_down Set-Cookie "^(.*)$" "\$1; Secure"
        }
    }
    @subscription path ${SUB_PATH}/* ${JSON_PATH}/* ${CLASH_PATH}/*
    handle @subscription {
        reverse_proxy 127.0.0.1:$SUB_PORT
    }
    handle {
        respond "Not Found" 404
    }
}
EOF
}

# CLI initialization creates the schema and hashes the random credentials.
# Subscription settings have no equivalent CLI flags in this pinned version.
# Write them in one parameterized transaction while the service is stopped.
configure_database() {
    python3 - "$1" "$DOMAIN" "$PANEL_PORT" "$SUB_PORT" \
        "$PANEL_PATH" "$SUB_PATH" "$JSON_PATH" "$CLASH_PATH" <<'PY'
import sqlite3
import sys
from pathlib import Path

db, domain, panel_port, sub_port, panel, sub, json_path, clash = sys.argv[1:]
if not Path(db).is_file():
    raise SystemExit("3x-ui 没有创建数据库，停止安装。")
settings = {
    "webListen": "127.0.0.1", "webPort": panel_port,
    "webDomain": domain, "webBasePath": panel + "/",
    "webCertFile": "", "webKeyFile": "",
    "trustedProxyCIDRs": "127.0.0.1/32,::1/128",
    "subEnable": "true", "subListen": "127.0.0.1", "subPort": sub_port,
    "subDomain": domain, "subCertFile": "", "subKeyFile": "",
    "subPath": sub + "/", "subURI": "https://" + domain + sub + "/",
    "subJsonEnable": "true", "subJsonPath": json_path + "/",
    "subJsonURI": "https://" + domain + json_path + "/",
    "subClashEnable": "true", "subClashPath": clash + "/",
    "subClashURI": "https://" + domain + clash + "/",
}
with sqlite3.connect(db) as conn:
    columns = {row[1] for row in conn.execute("PRAGMA table_info(settings)")}
    if not {"key", "value"} <= columns:
        raise SystemExit("数据库结构不兼容，停止安装。")
    if conn.execute("SELECT count(*) FROM users").fetchone()[0] != 1:
        raise SystemExit("初始管理员数量异常，停止安装。")
    for key, value in settings.items():
        conn.execute("DELETE FROM settings WHERE key = ?", (key,))
        conn.execute("INSERT INTO settings (key, value) VALUES (?, ?)", (key, value))
    actual = dict(conn.execute("SELECT key, value FROM settings"))
    if any(actual.get(key) != value for key, value in settings.items()):
        raise SystemExit("数据库设置回读失败。")
PY
}

configure_reality_inbound() {
    local db=${1:?database path required}
    local domain=${2:?domain required}
    local xray_binary=${3:?xray binary required}
    local output_json=${4:?output JSON path required}

    [[ -f "$db" ]] || { printf '错误：3x-ui 数据库不存在：%s\n' "$db" >&2; return 1; }
    [[ -x "$xray_binary" ]] || { printf '错误：Xray 不可执行：%s\n' "$xray_binary" >&2; return 1; }
    command -v python3 >/dev/null 2>&1 || { printf '错误：缺少 python3。\n' >&2; return 1; }

    # The Python transaction keeps the legacy JSON fields and v3.8 normalized
    # client tables consistent. Xray output is captured in memory; private keys
    # are never printed or written to the public result file.
    umask 077
    python3 - "$db" "$domain" "$xray_binary" "$output_json" <<'PY'
import json
import os
import re
import secrets
import sqlite3
import subprocess
import sys
import time
import urllib.parse
import uuid
from pathlib import Path

DB, DOMAIN, XRAY, OUTPUT = sys.argv[1:]
REMARK = "REALITY-443-Caddy"
PORT = 443
TARGET = "127.0.0.1:8443"
FLOW = "xtls-rprx-vision"


def fail(message):
    raise SystemExit("错误：" + message)


def parse_keypair(text):
    private_key = ""
    public_key = ""
    for line in text.splitlines():
        match = re.match(r"\s*([^:]+?)\s*:\s*(\S+)\s*$", line)
        if not match:
            continue
        label = re.sub(r"[^a-z]", "", match.group(1).lower())
        value = match.group(2)
        if label in {"privatekey", "private"}:
            private_key = value
        elif label in {"publickey", "public", "password", "passwordpublickey"}:
            public_key = value
    return private_key, public_key


def valid_key(value):
    return bool(re.fullmatch(r"[A-Za-z0-9_-]{40,48}={0,2}", value or ""))


def run_x25519(private_key=None):
    command = [XRAY, "x25519"]
    if private_key:
        command += ["-i", private_key]
    try:
        proc = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              text=True, timeout=15, check=False)
    except (OSError, subprocess.SubprocessError):
        fail("Xray x25519 执行失败或超时。")
    if proc.returncode != 0:
        fail("Xray x25519 执行失败。")
    generated_private, generated_public = parse_keypair(proc.stdout)
    if private_key:
        generated_private = private_key
    if not valid_key(generated_private) or not valid_key(generated_public):
        fail("无法解析 Xray x25519 输出的密钥对。")
    return generated_private, generated_public


def columns(conn, table):
    return {row[1] for row in conn.execute(f'PRAGMA table_info("{table}")')}


def require_columns(conn, table, required):
    actual = columns(conn, table)
    missing = sorted(set(required) - actual)
    if missing:
        fail(f"3x-ui v3.8.0 数据库结构不兼容：{table} 缺少 {', '.join(missing)}")
    return actual


def insert_known(conn, table, values, actual_columns):
    selected = [(key, value) for key, value in values.items() if key in actual_columns]
    names = ", ".join(f'"{key}"' for key, _ in selected)
    placeholders = ", ".join("?" for _ in selected)
    conn.execute(f'INSERT INTO "{table}" ({names}) VALUES ({placeholders})',
                 tuple(value for _, value in selected))


def json_object(raw, label):
    try:
        value = json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        fail(f"已有 {REMARK} 的 {label} 不是有效 JSON，为避免损坏已停止。")
    if not isinstance(value, dict):
        fail(f"已有 {REMARK} 的 {label} 结构无效。")
    return value


def valid_uuid(value):
    try:
        uuid.UUID(value)
        return True
    except (ValueError, TypeError, AttributeError):
        return False


db_path = Path(DB)
if not db_path.is_file():
    fail("3x-ui 数据库不存在。")

conn = sqlite3.connect(DB, timeout=15, isolation_level=None)
conn.row_factory = sqlite3.Row
try:
    inbound_cols = require_columns(conn, "inbounds", {
        "id", "user_id", "up", "down", "total", "remark", "enable",
        "expiry_time", "listen", "port", "protocol", "settings",
        "stream_settings", "tag", "sniffing",
    })
    client_cols = require_columns(conn, "clients", {
        "id", "email", "sub_id", "uuid", "flow", "enable", "created_at", "updated_at",
    })
    link_cols = require_columns(conn, "client_inbounds", {
        "client_id", "inbound_id", "flow_override", "created_at",
    })
    traffic_cols = require_columns(conn, "client_traffics", {
        "id", "inbound_id", "enable", "email", "up", "down", "expiry_time", "total",
    })
    require_columns(conn, "users", {"id"})

    conn.execute("BEGIN IMMEDIATE")
    owned = conn.execute("SELECT * FROM inbounds WHERE remark = ? ORDER BY id", (REMARK,)).fetchall()
    if len(owned) > 1:
        fail(f"发现多个同名入站 {REMARK}，请先在面板中处理。")
    current = owned[0] if owned else None
    current_id = current["id"] if current else -1
    conflict = conn.execute(
        "SELECT id, remark, protocol FROM inbounds WHERE port = ? AND id <> ? ORDER BY id LIMIT 1",
        (PORT, current_id),
    ).fetchone()
    if conflict:
        fail(f"TCP 443 已被其他 3x-ui 入站占用（ID {conflict['id']}, {conflict['remark'] or conflict['protocol']}）。")

    if current:
        if current["protocol"] != "vless":
            fail(f"已有同名入站的协议不是 VLESS，拒绝覆盖。")
        stream = json_object(current["stream_settings"], "streamSettings")
        if stream.get("security") != "reality" or stream.get("network") not in {"tcp", "raw"}:
            fail(f"已有同名入站不是 TCP/RAW + REALITY，拒绝覆盖。")
        reality = stream.get("realitySettings")
        if not isinstance(reality, dict):
            fail("已有同名入站缺少 realitySettings。")
        private_key = reality.get("privateKey", "")
        if not valid_key(private_key):
            fail("已有同名入站的 REALITY 私钥无效，拒绝重置身份。")
        client_hints = reality.get("settings")
        if not isinstance(client_hints, dict):
            client_hints = {}
        # Derive from the existing private key: stale public hints must not
        # silently produce an unusable import link. This does not rotate keys.
        _, public_key = run_x25519(private_key)
        short_ids = reality.get("shortIds")
        if (not isinstance(short_ids, list) or not short_ids
                or any(not isinstance(s, str) or not re.fullmatch(r"(?:[0-9a-fA-F]{2}){0,8}", s) for s in short_ids)
                or not short_ids[0]):
            fail("已有同名入站的 REALITY shortId 无效，拒绝重置身份。")
        short_id = str(short_ids[0]).lower()

        # Normalized tables are authoritative in 3x-ui v3.8.0. Pick the first
        # valid attached client for output while preserving every client/link.
        attached = conn.execute(
            "SELECT c.id, c.email, c.sub_id, c.uuid, c.enable, ci.flow_override "
            "FROM client_inbounds ci JOIN clients c ON c.id = ci.client_id "
            "WHERE ci.inbound_id = ? ORDER BY c.id",
            (current_id,),
        ).fetchall()
        selected = next((row for row in attached
                         if row["enable"] and row["email"] and row["sub_id"] and valid_uuid(row["uuid"])
                         and row["flow_override"] == FLOW), None)
        if selected is None:
            fail("已有同名入站没有启用 xtls-rprx-vision 的有效已关联客户端，拒绝重置身份。")
        client_uuid, email, sub_id = selected["uuid"], selected["email"], selected["sub_id"]

        # Repair only the routing/public hints the installer owns. Keep keys,
        # short IDs, all clients, counters and unrelated stream options intact.
        stream["network"] = "tcp"
        stream["security"] = "reality"
        reality["target"] = TARGET
        reality.pop("dest", None)
        reality["xver"] = 0
        reality["serverNames"] = [DOMAIN]
        client_hints.update({
            "publicKey": public_key, "fingerprint": "chrome",
            "serverName": DOMAIN, "spiderX": client_hints.get("spiderX") or "/",
        })
        reality["settings"] = client_hints
        stream["realitySettings"] = reality
        conn.execute(
            "UPDATE inbounds SET listen = ?, port = ?, enable = 1, stream_settings = ? WHERE id = ?",
            ("0.0.0.0", PORT, json.dumps(stream, separators=(",", ":")), current_id),
        )
        inbound_id = current_id
    else:
        private_key, public_key = run_x25519()
        short_id = secrets.token_hex(8)
        client_uuid = str(uuid.uuid4())
        sub_id = secrets.token_urlsafe(16)
        while True:
            email = "reality-" + secrets.token_hex(5)
            if conn.execute("SELECT 1 FROM clients WHERE email = ?", (email,)).fetchone() is None:
                break
        now = int(time.time() * 1000)
        client = {
            "id": client_uuid, "flow": FLOW, "email": email, "limitIp": 0,
            "totalGB": 0, "expiryTime": 0, "enable": True, "tgId": 0,
            "subId": sub_id, "comment": "", "reset": 0,
            "created_at": now, "updated_at": now,
        }
        settings = {"clients": [client], "decryption": "none", "encryption": "none", "fallbacks": []}
        stream = {
            "network": "tcp", "security": "reality",
            "tcpSettings": {"acceptProxyProtocol": False, "header": {"type": "none"}},
            "realitySettings": {
                "show": False, "xver": 0, "target": TARGET, "serverNames": [DOMAIN],
                "privateKey": private_key, "minClientVer": "", "maxClientVer": "",
                "maxTimediff": 0, "shortIds": [short_id], "mldsa65Seed": "",
                "settings": {"publicKey": public_key, "fingerprint": "chrome",
                             "serverName": DOMAIN, "spiderX": "/", "mldsa65Verify": ""},
            },
        }
        user_row = conn.execute("SELECT id FROM users ORDER BY id LIMIT 1").fetchone()
        if user_row is None:
            fail("3x-ui 数据库中没有管理员，无法创建入站。")
        while True:
            tag = "inbound-443-reality-" + secrets.token_hex(4)
            if conn.execute("SELECT 1 FROM inbounds WHERE tag = ?", (tag,)).fetchone() is None:
                break
        inbound_values = {
            "user_id": user_row["id"], "up": 0, "down": 0, "total": 0, "remark": REMARK,
            "sub_sort_index": 1, "enable": 1, "expiry_time": 0, "traffic_reset": "never",
            "traffic_reset_day": 1, "last_traffic_reset_time": 0,
            "listen": "0.0.0.0", "port": PORT, "protocol": "vless",
            "settings": json.dumps(settings, separators=(",", ":")),
            "stream_settings": json.dumps(stream, separators=(",", ":")),
            "tag": tag, "sniffing": json.dumps({"enabled": False}, separators=(",", ":")),
            "share_addr_strategy": "node", "share_addr": "", "disable_flow": 0,
            "origin_node_guid": "",
        }
        insert_known(conn, "inbounds", inbound_values, inbound_cols)
        inbound_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

        client_values = {
            "email": email, "sub_id": sub_id, "uuid": client_uuid, "password": "",
            "auth": "", "flow": FLOW, "security": "", "reverse": "",
            "wg_private_key": "", "wg_public_key": "", "wg_allowed_ips": "",
            "wg_pre_shared_key": "", "wg_keep_alive": 0, "wg_forwarded_ports": "",
            "secret": "", "ad_tag": "", "limit_ip": 0, "limit_hwid": 0,
            "total_gb": 0, "expiry_time": 0, "enable": 1, "tg_id": 0,
            "group_name": "", "comment": "", "reset": 0, "reset_day": 0,
            "reset_max": 0, "traffic_reset": "never", "traffic_reset_day": 1,
            "created_at": now, "updated_at": now, "sync_orphaned_at": 0,
        }
        insert_known(conn, "clients", client_values, client_cols)
        client_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]
        insert_known(conn, "client_inbounds", {
            "client_id": client_id, "inbound_id": inbound_id,
            "flow_override": FLOW, "created_at": now,
        }, link_cols)
        insert_known(conn, "client_traffics", {
            "inbound_id": inbound_id, "enable": 1, "email": email,
            "up": 0, "down": 0, "expiry_time": 0, "total": 0, "reset": 0,
            "reset_day": 0, "reset_max": 0, "reset_count": 0,
            "last_online": 0, "last_sub_fetch": 0,
        }, traffic_cols)

    # Verify the identity mapping before committing. This catches partial or
    # schema-surprise writes while rollback is still possible.
    check = conn.execute(
        "SELECT i.port, i.protocol, c.uuid, c.sub_id, ci.flow_override, t.up, t.down "
        "FROM inbounds i JOIN client_inbounds ci ON ci.inbound_id = i.id "
        "JOIN clients c ON c.id = ci.client_id "
        "LEFT JOIN client_traffics t ON t.inbound_id = i.id AND t.email = c.email "
        "WHERE i.id = ? AND c.email = ?",
        (inbound_id, email),
    ).fetchone()
    if not check or check["port"] != PORT or check["protocol"] != "vless" or check["uuid"] != client_uuid:
        fail("REALITY 入站数据库回读验证失败。")
    conn.execute("COMMIT")
except BaseException:
    if conn.in_transaction:
        conn.execute("ROLLBACK")
    raise
finally:
    conn.close()

query = urllib.parse.urlencode({
    "type": "tcp", "security": "reality", "pbk": public_key,
    "fp": "chrome", "sni": DOMAIN, "sid": short_id,
    "spx": "/", "flow": FLOW,
})
vless_uri = f"vless://{client_uuid}@{DOMAIN}:{PORT}?{query}#{urllib.parse.quote(REMARK)}"
result = {
    "inbound_id": inbound_id, "uuid": client_uuid, "public_key": public_key,
    "short_id": short_id, "server_name": DOMAIN, "port": PORT,
    "email": email, "sub_id": sub_id, "vless_uri": vless_uri,
}
output_path = Path(OUTPUT)
output_path.parent.mkdir(parents=True, exist_ok=True)
temporary = output_path.with_name(output_path.name + ".tmp-" + secrets.token_hex(4))
try:
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, output_path)
    os.chmod(output_path, 0o600)
finally:
    try:
        temporary.unlink()
    except FileNotFoundError:
        pass
PY
}

verify_login() {
    python3 - "$DOMAIN" "$PANEL_PORT" "$PANEL_PATH" "$1" "$2" <<'PY'
import http.cookiejar
import json
import sys
import urllib.parse
import urllib.request

domain, port, path, username, password = sys.argv[1:]
client = urllib.request.build_opener(
    urllib.request.ProxyHandler({}),
    urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()),
)
base = "http://127.0.0.1:" + port + path
req = urllib.request.Request(base + "/csrf-token", headers={"Host": domain})
with client.open(req, timeout=10) as response:
    token = json.load(response)["obj"]
payload = urllib.parse.urlencode({"username": username, "password": password}).encode()
req = urllib.request.Request(base + "/login", data=payload,
                             headers={"Host": domain, "X-CSRF-Token": token})
with client.open(req, timeout=10) as response:
    if json.load(response).get("success") is not True:
        raise SystemExit("随机管理员凭据验证失败。")
print("随机管理员凭据验证通过。")
PY
}

cleanup() {
    local status=$?
    trap - EXIT
    if (( status != 0 && COMPLETE == 0 )); then
        if (( MIGRATION_STARTED )); then
            rollback_migration
            printf '\n迁移失败，已尝试恢复原配置和服务状态。备份：%s\n' "$BACKUP_DIR" >&2
            exit "$status"
        fi
        if (( XUI_OWNED )); then
            systemctl disable --now x-ui >/dev/null 2>&1 || true
        fi
        if (( CADDY_CONFIGURED )); then
            systemctl disable --now caddy >/dev/null 2>&1 || true
        fi
        if (( CADDY_MASKED )); then
            systemctl unmask caddy >/dev/null 2>&1 || true
        fi
        printf '\n安装未完成。已停用本次配置的服务；文件和日志保留以便排查。\n' >&2
        printf '查看日志：journalctl -u x-ui -u caddy -n 80 --no-pager\n' >&2
        [[ -z "$WORK_DIR" ]] || printf '本次工作目录：%s\n' "$WORK_DIR" >&2
    elif [[ -n "$WORK_DIR" ]]; then
        rm -rf -- "$WORK_DIR"
    fi
    exit "$status"
}

port_busy() {
    [[ -n "$(ss -H -ltn "sport = :$1")" || -n "$(ss -H -lun "sport = :$1")" ]]
}

check_loopback() {
    local port="$1" addresses
    addresses=$(ss -H -ltn "sport = :$port" | awk '{print $4}')
    [[ "$addresses" == "127.0.0.1:$port" ]] || \
        die "端口 $port 未严格绑定 127.0.0.1，已拒绝完成安装。"
}

download() {
    curl --fail --location --silent --show-error --retry 3 \
        --connect-timeout 15 --max-time 600 --proto '=https' --proto-redir '=https' \
        --output "$2" "$1"
}

update_system() {
    log '更新软件源索引；任一软件源更新失败时停止安装。'
    export DEBIAN_FRONTEND=noninteractive
    apt-get -o APT::Update::Error-Mode=any update
    if [[ "$ID" == ubuntu ]]; then
        log '升级 Ubuntu 已安装的软件包，保留已有配置文件。'
        apt-get -o DPkg::Lock::Timeout=120 \
            -o Dpkg::Options::=--force-confdef \
            -o Dpkg::Options::=--force-confold upgrade -y
    fi
}

wait_panel() {
    local attempt
    for attempt in {1..30}; do
        if curl --noproxy '*' -fsS --max-time 2 -H "Host: $DOMAIN" \
            "http://127.0.0.1:$PANEL_PORT${PANEL_PATH}/" -o /dev/null 2>/dev/null && \
            [[ -n "$(ss -H -ltn "sport = :$SUB_PORT")" && -n "$(ss -H -ltn 'sport = :443')" ]]; then
            return 0
        fi
        sleep 1
    done
    die '面板、订阅或 REALITY 443 入站未正常启动。'
}

check_shared_listeners() {
    check_loopback "$PANEL_PORT"
    check_loopback "$SUB_PORT"
    check_loopback "$CADDY_TLS_PORT"
    local listeners
    listeners=$(ss -H -ltnp 'sport = :443')
    [[ "$listeners" == *xray* && "$listeners" != *caddy* ]] || die '公网 TCP 443 未由 Xray 独占。'
}

wait_public_https() {
    local attempt
    log '验证公网 443 → REALITY → Caddy → 面板，等待证书最多约 90 秒。'
    for attempt in {1..18}; do
        if curl --noproxy '*' -fsS --connect-timeout 2 --max-time 3 \
            --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN${PANEL_PATH}/" -o /dev/null 2>/dev/null; then
            return 0
        fi
        sleep 2
    done
    return 1
}

write_node_access() {
    # Public key and UUID are sufficient for importing; the private key stays in DB.
    python3 - "$NODE_INFO" "$DOMAIN" "$SUB_PATH" <<'PY'
import json
import os
import sys
from pathlib import Path

path, domain, sub_path = sys.argv[1:]
data = json.loads(Path(path).read_text())
data["subscription_url"] = "https://" + domain + sub_path + "/" + data["sub_id"]
Path(path).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
os.chmod(path, 0o600)
PY
}

read_existing_layout() {
    python3 - /etc/x-ui/x-ui.db "$DOMAIN" <<'PY'
import re
import sqlite3
import sys

db, domain = sys.argv[1:]
with sqlite3.connect("file:" + db + "?mode=ro", uri=True) as conn:
    settings = dict(conn.execute("SELECT key, value FROM settings"))
required = {"webListen": "127.0.0.1", "webPort": "2053", "subListen": "127.0.0.1",
            "subPort": "2096", "webDomain": domain, "subDomain": domain,
            "webCertFile": "", "webKeyFile": "", "subCertFile": "", "subKeyFile": ""}
if any(settings.get(key) != value for key, value in required.items()):
    raise SystemExit("已有监听地址、域名或 TLS 设置与旧脚本不符，请勿自动迁移。")
paths = [settings.get(key, "") for key in ("webBasePath", "subPath", "subJsonPath", "subClashPath")]
if len(set(paths)) != 4 or any(not re.fullmatch(r"/[a-zA-Z0-9_-]+/", p) for p in paths):
    raise SystemExit("已有访问路径不符合本脚本格式，拒绝覆盖。")
for key, path in zip(("subURI", "subJsonURI", "subClashURI"), paths[1:]):
    if settings.get(key) != "https://" + domain + path:
        raise SystemExit("公开订阅地址与域名不符，拒绝自动迁移。")
print("\n".join(path.rstrip("/") for path in paths))
PY
}

rollback_migration() {
    local failed=0
    log '回滚本次迁移，恢复数据库、Caddyfile 和服务状态。'
    # If the initial stop only partly succeeds, all configuration is untouched.
    # Restart original services without retrying the failed stop or writing DB.
    if (( MIGRATION_MUTATED == 0 )); then
        if [[ "$CADDY_WAS_ACTIVE" == active ]]; then systemctl start caddy || failed=1; fi
        if [[ "$XUI_WAS_ACTIVE" == active ]]; then systemctl start x-ui || failed=1; fi
        if (( failed )); then
            printf '配置未修改，但原服务未全部恢复，请查看 systemctl status x-ui caddy。\n' >&2
        fi
        return 0
    fi
    systemctl stop x-ui caddy || failed=1
    if (( failed )); then
        printf '无法停止服务，未覆盖正在使用的数据库。请使用备份手动恢复：%s\n' "$BACKUP_DIR" >&2
        return 0
    fi
    if (( MIGRATION_DB_READY )); then
        # Restore with SQLite's backup API, including any existing WAL state.
        python3 - "$BACKUP_DIR/x-ui.db" /etc/x-ui/x-ui.db <<'PY' || failed=1
import sqlite3
import sys
with sqlite3.connect(sys.argv[1]) as src, sqlite3.connect(sys.argv[2]) as dst:
    src.backup(dst)
PY
    fi
    cp -a "$BACKUP_DIR/Caddyfile" /etc/caddy/Caddyfile || failed=1
    if [[ -f "$BACKUP_DIR/node.json" ]]; then
        cp -a "$BACKUP_DIR/node.json" "$NODE_INFO" || failed=1
    else
        rm -f -- "$NODE_INFO" || failed=1
    fi
    if (( failed )); then
        printf '恢复文件失败，服务保持停止。请使用备份手动恢复：%s\n' "$BACKUP_DIR" >&2
        return 0
    fi
    if [[ "$CADDY_WAS_ACTIVE" == active ]]; then systemctl start caddy || failed=1; fi
    if [[ "$XUI_WAS_ACTIVE" == active ]]; then systemctl start x-ui || failed=1; fi
    if (( failed )); then
        printf '回滚有失败项，请查看服务日志并用备份恢复：%s\n' "$BACKUP_DIR" >&2
    fi
}

check_migration_ports() {
    python3 - "$1" <<'PY'
import json
from pathlib import Path
import re
import subprocess
import sys
import urllib.request

groups = {}
for service in ("x-ui", "caddy"):
    value = subprocess.check_output(["systemctl", "show", service, "-p", "ControlGroup", "--value"], text=True).strip()
    if value:
        groups[service] = value
for port, services in ((80, ("caddy",)), (443, ("caddy", "x-ui")),
                       (8443, ("caddy",)), (2019, ("caddy",))):
    for network in ("-ltnp", "-lunp"):
        output = subprocess.check_output(["ss", "-H", network, "sport = :" + str(port)], text=True)
        for line in output.splitlines():
            pids = re.findall(r"pid=(\d+)", line)
            if not pids:
                raise SystemExit("无法确认端口 %s 所属服务。" % port)
            for pid in pids:
                actual = [s.split(":", 2)[2] for s in Path("/proc/" + pid + "/cgroup").read_text().splitlines()]
                if not any(g == groups[s] or g.startswith(groups[s] + "/")
                           for s in services if s in groups for g in actual):
                    raise SystemExit("端口 %s 被本脚本服务以外的进程占用。" % port)
if subprocess.run(["systemctl", "is-active", "--quiet", "caddy"]).returncode == 0:
    client = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    with client.open("http://127.0.0.1:2019/config/", timeout=5) as response:
        live = json.load(response)
    with open(sys.argv[1]) as file:
        if live != json.load(file):
            raise SystemExit("Caddy 实际运行配置与磁盘配置不同，拒绝覆盖。")
PY
}

migrate_existing() {
    local layout candidate match=0 xui_version
    local -a paths
    [[ -f /etc/x-ui/x-ui.db && -f /etc/caddy/Caddyfile && -f /etc/systemd/system/x-ui.service ]] || \
        die '--migrate 仅适用于本脚本安装的已有服务。'
    grep -qF 'Description=3x-ui panel (Caddy reverse proxy)' /etc/systemd/system/x-ui.service || \
        die 'x-ui 服务单元与本脚本不符。'
    xui_version=$(/usr/local/x-ui/x-ui -v)
    [[ "$xui_version" == "${XUI_VERSION#v}" || "$xui_version" == "$XUI_VERSION" ]] || \
        die "迁移只支持 $XUI_VERSION，当前版本：$xui_version"
    [[ -x "$XRAY_BINARY" ]] || die '未找到对应的 Xray 二进制。'
    layout=$(read_existing_layout) || die '无法读取兼容的旧安装配置。'
    mapfile -t paths <<< "$layout"
    PANEL_PATH=${paths[0]} SUB_PATH=${paths[1]} JSON_PATH=${paths[2]} CLASH_PATH=${paths[3]}
    WORK_DIR=$(mktemp -d /tmp/3x-ui-caddy.XXXXXXXX)
    trap cleanup EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM
    render_legacy_caddyfile > "$WORK_DIR/legacy.Caddyfile"
    render_caddyfile > "$WORK_DIR/Caddyfile"
    caddy adapt --config /etc/caddy/Caddyfile --adapter caddyfile > "$WORK_DIR/existing.json"
    for candidate in legacy.Caddyfile Caddyfile; do
        caddy adapt --config "$WORK_DIR/$candidate" --adapter caddyfile > "$WORK_DIR/candidate.json"
        if python3 - "$WORK_DIR/existing.json" "$WORK_DIR/candidate.json" <<'PY'
import json
import sys
with open(sys.argv[1]) as a, open(sys.argv[2]) as b:
    sys.exit(0 if json.load(a) == json.load(b) else 1)
PY
        then match=1; break; fi
    done
    (( match )) || die 'Caddyfile 含非本脚本的配置，拒绝覆盖其他站点。'
    caddy fmt --overwrite "$WORK_DIR/Caddyfile"
    caddy validate --config "$WORK_DIR/Caddyfile" --adapter caddyfile
    check_migration_ports "$WORK_DIR/existing.json"
    BACKUP_DIR=$(mktemp -d /root/3x-ui-caddy-backup.XXXXXXXX)
    cp -a /etc/caddy/Caddyfile "$BACKUP_DIR/Caddyfile"
    if [[ -f "$NODE_INFO" ]]; then cp -a "$NODE_INFO" "$BACKUP_DIR/node.json"; fi
    XUI_WAS_ACTIVE=$(systemctl is-active x-ui || true)
    CADDY_WAS_ACTIVE=$(systemctl is-active caddy || true)
    printf 'x-ui=%s\ncaddy=%s\n' "$XUI_WAS_ACTIVE" "$CADDY_WAS_ACTIVE" > "$BACKUP_DIR/service-state.txt"
    MIGRATION_STARTED=1
    systemctl stop x-ui caddy
    for candidate in 80 443 8443; do
        port_busy "$candidate" && die "停止服务后端口 $candidate 仍被占用，取消迁移。"
    done
    python3 - /etc/x-ui/x-ui.db "$BACKUP_DIR/x-ui.db" <<'PY'
import sqlite3
import sys
with sqlite3.connect(sys.argv[1]) as src, sqlite3.connect(sys.argv[2]) as dst:
    src.backup(dst)
PY
    MIGRATION_DB_READY=1
    MIGRATION_MUTATED=1
    configure_reality_inbound /etc/x-ui/x-ui.db "$DOMAIN" "$XRAY_BINARY" "$NODE_INFO"
    write_node_access
    install -o root -g caddy -m 640 "$WORK_DIR/Caddyfile" /etc/caddy/Caddyfile
    systemctl start caddy
    systemctl start x-ui
    wait_panel
    systemctl is-active --quiet x-ui caddy || die '迁移后服务未处于运行状态。'
    check_shared_listeners
    wait_public_https || die '迁移后 HTTPS 443 验证失败，将恢复原配置。'
    COMPLETE=1
    log '迁移完成：面板、订阅和 REALITY 节点现共用公网 TCP 443。'
    printf '面板：https://%s%s/\n节点：sudo cat %s\n备份：%s\n' "$DOMAIN" "$PANEL_PATH" "$NODE_INFO" "$BACKUP_DIR"
    printf '原管理员、访问路径和其他入站保持不变；其他入站原来开放的端口仍需单独管理。\n'
}

main() {
    local render=0 migrate=0 arch checksum item username password ready=0
    case "${1:-}" in
        -h|--help) usage; return 0 ;;
        --render) render=1; shift ;;
        --migrate) migrate=1; shift ;;
    esac
    (( $# <= 1 )) || die '只接受一个域名参数。'
    DOMAIN="${1:-}"
    if [[ -z "$DOMAIN" ]]; then
        [[ -t 0 ]] || die '请提供域名，例如：sudo bash install-3x-ui-caddy.sh panel.example.com'
        read -r -p '请输入面板域名或网址（例如 https://panel.example.com）：' DOMAIN
    fi
    DOMAIN=$(normalize_domain_input "$DOMAIN")
    validate_domain "$DOMAIN" || die '请输入有效域名或 http(s) 网址；不支持页面路径、查询参数或非 443 端口，中文域名请使用 punycode。'
    if (( render )); then
        PANEL_PATH=/panel-preview SUB_PATH=/sub-preview
        JSON_PATH=/json-preview CLASH_PATH=/clash-preview
        render_caddyfile
        return 0
    fi

    [[ $EUID -eq 0 ]] || die '请使用 root 或 sudo 运行。'
    [[ "$(uname -s)" == Linux ]] || die '安装目标必须为 Linux。'
    [[ -d /run/systemd/system ]] || die '需要正在运行的 systemd。'
    command -v flock >/dev/null || die '缺少 flock，请安装 util-linux。'
    exec 9>/run/lock/3x-ui-caddy-install.lock
    flock -n 9 || die '另一个安装任务正在运行。'
    # shellcheck disable=SC1091
    source /etc/os-release
    case "${ID:-}:${VERSION_ID:-}" in
        debian:*) [[ "${VERSION_ID%%.*}" =~ ^[0-9]+$ ]] && (( ${VERSION_ID%%.*} >= 12 )) || die '需要 Debian 12+。' ;;
        ubuntu:*) [[ "${VERSION_ID%%.*}" =~ ^[0-9]+$ ]] && (( ${VERSION_ID%%.*} >= 22 )) || die '需要 Ubuntu 22.04+。' ;;
        *) die '此脚本支持 Debian 12+ / Ubuntu 22.04+。' ;;
    esac
    case "$(uname -m)" in
        x86_64) arch=amd64; checksum=236b837627520f0c4ae4134dc6a34ea5e294b69e158879795fe8cd51c5f3582c ;;
        aarch64|arm64) arch=arm64; checksum=e93b7a6ba83bace11c5bf2192a15ae0eec24b1c02496567149fce0d223aba309 ;;
        *) die '当前只支持 amd64 / arm64。' ;;
    esac
    XRAY_BINARY="/usr/local/x-ui/bin/xray-linux-$arch"
    for item in $(compgen -e); do
        [[ "$item" != XUI_* ]] || die "请清除已有环境变量 $item 后重试。"
    done
    command -v ss >/dev/null || die '缺少 ss，请先安装 iproute2。'
    if (( migrate )); then
        migrate_existing
        return 0
    fi

    # Refuse existing state instead of treating a second run as an upgrade.
    for item in /usr/local/x-ui /etc/x-ui /usr/bin/x-ui /usr/local/bin/x-ui \
        /etc/default/x-ui /etc/sysconfig/x-ui /etc/conf.d/x-ui \
        /etc/caddy /root/3x-ui-caddy-access.txt "$NODE_INFO" \
        /etc/apt/sources.list.d/caddy-stable.list \
        /usr/share/keyrings/caddy-stable-archive-keyring.gpg; do
        [[ ! -e "$item" && ! -L "$item" ]] || die "检测到已有文件 $item。此脚本只用于全新安装。"
    done
    for item in x-ui caddy; do
        if command -v "$item" >/dev/null 2>&1 || \
            [[ "$(systemctl show "$item.service" -p LoadState --value)" != not-found ]]; then
            die "检测到已有 $item，停止以保护现有配置。"
        fi
    done
    for item in 80 443 2019 "$CADDY_TLS_PORT" "$PANEL_PORT" "$SUB_PORT"; do
        port_busy "$item" && die "端口 $item 已被占用，请先处理冲突。"
    done
    trap cleanup EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM
    WORK_DIR=$(mktemp -d /tmp/3x-ui-caddy.XXXXXXXX)

    update_system
    log '安装基础工具；下载固定版本的官方发行包并校验 SHA-256。'
    apt-get install -y ca-certificates curl gnupg debian-keyring \
        debian-archive-keyring apt-transport-https python3 tar openssl iproute2
    download "https://github.com/MHSanaei/3x-ui/releases/download/$XUI_VERSION/x-ui-linux-$arch.tar.gz" "$WORK_DIR/x-ui.tar.gz"
    printf '%s  %s\n' "$checksum" "$WORK_DIR/x-ui.tar.gz" | sha256sum --check --status || die '3x-ui 发行包校验失败。'
    tar -xzf "$WORK_DIR/x-ui.tar.gz" -C "$WORK_DIR"
    [[ -f "$WORK_DIR/x-ui/x-ui" && -d "$WORK_DIR/x-ui/bin" ]] || die '发行包结构不符合预期。'

    username="u$(openssl rand -hex 5)"
    password=$(openssl rand -hex 18)
    PANEL_PATH="/panel-$(openssl rand -hex 12)"
    SUB_PATH="/sub-$(openssl rand -hex 12)"
    JSON_PATH="/json-$(openssl rand -hex 12)"
    CLASH_PATH="/clash-$(openssl rand -hex 12)"
    install -d -m 700 /etc/x-ui
    mv "$WORK_DIR/x-ui" /usr/local/x-ui
    chmod 755 /usr/local/x-ui/x-ui
    find /usr/local/x-ui/bin -maxdepth 1 -type f -name 'xray-linux-*' -exec chmod 755 {} +
    [[ ! -f /usr/local/x-ui/x-ui.sh ]] || install -m 755 /usr/local/x-ui/x-ui.sh /usr/bin/x-ui
    export XUI_DB_FOLDER=/etc/x-ui XUI_DB_TYPE=sqlite
    (
        cd /usr/local/x-ui
        ./x-ui setting -username "$username" -password "$password" \
            -port "$PANEL_PORT" -listenIP 127.0.0.1 -webBasePath "${PANEL_PATH}/"
    ) > "$WORK_DIR/initialize.log" 2>&1
    configure_database /etc/x-ui/x-ui.db
    configure_reality_inbound /etc/x-ui/x-ui.db "$DOMAIN" "$XRAY_BINARY" "$NODE_INFO"
    write_node_access
    chmod 600 /etc/x-ui/x-ui.db

    cat > /root/3x-ui-caddy-access.txt <<EOF
3x-ui $XUI_VERSION + Caddy
面板：https://$DOMAIN${PANEL_PATH}/
用户名：$username
密码：$password
普通订阅：https://$DOMAIN${SUB_PATH}/<客户端订阅ID>
JSON 订阅：https://$DOMAIN${JSON_PATH}/<客户端订阅ID>
Clash 订阅：https://$DOMAIN${CLASH_PATH}/<客户端订阅ID>
面板监听：127.0.0.1:$PANEL_PORT
订阅监听：127.0.0.1:$SUB_PORT
Caddy HTTPS：127.0.0.1:$CADDY_TLS_PORT
REALITY 入站：公网 TCP 443（REALITY-443-Caddy）
节点与订阅导入信息：$NODE_INFO
EOF
    chmod 600 /root/3x-ui-caddy-access.txt

    cat > "$WORK_DIR/x-ui.service" <<'EOF'
[Unit]
Description=3x-ui panel (Caddy reverse proxy)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/usr/local/x-ui
Environment=XUI_DB_FOLDER=/etc/x-ui
Environment=XUI_DB_TYPE=sqlite
ExecStart=/usr/local/x-ui/x-ui
Restart=on-failure
RestartSec=5s
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
    install -m 644 "$WORK_DIR/x-ui.service" /etc/systemd/system/x-ui.service
    XUI_OWNED=1
    systemctl daemon-reload

    log '从 Caddy 官方软件源安装；生成 HTTPS 反向代理配置。'
    download 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' "$WORK_DIR/caddy.asc"
    gpg --batch --yes --dearmor --output "$WORK_DIR/caddy.gpg" "$WORK_DIR/caddy.asc"
    install -m 644 "$WORK_DIR/caddy.gpg" /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    download 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' "$WORK_DIR/caddy.list"
    install -m 644 "$WORK_DIR/caddy.list" /etc/apt/sources.list.d/caddy-stable.list
    apt-get update
    # Prevent the package post-install hook from exposing its default site.
    CADDY_CONFIGURED=1
    systemctl mask caddy.service
    CADDY_MASKED=1
    apt-get install -y caddy
    cp -a /etc/caddy/Caddyfile "$WORK_DIR/Caddyfile.package-default"
    render_caddyfile > "$WORK_DIR/Caddyfile"
    caddy fmt --overwrite "$WORK_DIR/Caddyfile"
    caddy validate --config "$WORK_DIR/Caddyfile" --adapter caddyfile
    install -o root -g caddy -m 640 "$WORK_DIR/Caddyfile" /etc/caddy/Caddyfile

    log '启动本机 Caddy HTTPS 和公网 REALITY 443 入站。'
    systemctl unmask caddy.service
    CADDY_MASKED=0
    systemctl enable --now caddy
    systemctl enable --now x-ui
    wait_panel
    check_shared_listeners
    verify_login "$username" "$password"
    systemctl is-active --quiet x-ui caddy || die '服务未处于运行状态。'

    ready=0
    if wait_public_https; then ready=1; fi
    check_shared_listeners
    systemctl is-active --quiet x-ui caddy || die '等待证书期间服务停止，安装未完成。'
    if (( ready == 0 )) && curl --noproxy '*' -fsS --connect-timeout 2 --max-time 5 \
        --connect-to "$DOMAIN:443:127.0.0.1:$CADDY_TLS_PORT" "https://$DOMAIN${PANEL_PATH}/" -o /dev/null 2>/dev/null; then
        die 'Caddy HTTPS 已就绪，但 REALITY 443 回落验证失败。'
    fi
    # TLS pending is recoverable: leave Caddy running so ACME can retry.
    COMPLETE=1
    if (( ready )); then
        log '安装完成：面板、订阅和 REALITY 入站共用公网 TCP 443。'
    else
        log '服务已安装且内部端口已绑定本机；HTTPS 尚未验证成功。'
        printf '请检查域名 A/AAAA、云安全组和 TCP 80/443；Caddy 会自动重试签发证书。\n'
    fi
    printf '\n面板：https://%s%s/\n' "$DOMAIN" "$PANEL_PATH"
    printf '用户名和密码：sudo cat /root/3x-ui-caddy-access.txt\n'
    printf '节点及订阅导入信息：sudo cat %s\n' "$NODE_INFO"
    printf '配置：/etc/caddy/Caddyfile\n日志：journalctl -u x-ui -u caddy -n 80 --no-pager\n'
    printf '仍需在外部设备验证域名可访问、2053/2096/8443 不可直连。\n'
    if [[ -f /var/run/reboot-required ]]; then
        printf '系统更新提示需要重启，请在安装完成后择机手动重启服务器。\n'
    fi
    (( ready )) || return 2
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
